name: CI Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        python -c "import app; print('✅ App imports successfully')"
        python -c "from ifixit_repair_guide import IFixitRepairGuide; print('✅ Core module imports successfully')"
        python -c "from deepseek_summarizer import DeepSeekSummarizer; print('✅ DeepSeek module imports successfully')"
    
    - name: Test API endpoints
      run: |
        python -m uvicorn app:app --host 127.0.0.1 --port 8000 &
        sleep 5
        curl -f http://127.0.0.1:8000/health || exit 1
        echo "✅ Health endpoint works" 